version: '3.8'

services:
    mongo:
        image: mongo:latest
        restart: always
        container_name: contentizer_mongo
        ports:
            - "27017:27017"
        volumes:
            - ./docker/mongo_data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootpassword
        